# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculation_app_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ssp_eq_mws_sfr as sspeq
import pandas as pd


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # # mainWindow
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1110, 586)
        MainWindow.setFixedSize(1110, 586)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # # scroll area

        self.scrollArea_Wells_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_Wells_Area.setGeometry(QtCore.QRect(530, 370, 531, 161))
        self.scrollArea_Wells_Area.setWidgetResizable(True)
        self.scrollArea_Wells_Area.setObjectName("scrollArea_Wells_Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 508, 263))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # grid
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        # contents
        self.lineEdit_Welli_Skin_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_7.setObjectName("lineEdit_Welli_Skin_7")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_7, 6, 5, 1, 1)

        self.lineEdit_Welli_Ri_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_2.setObjectName("lineEdit_Welli_Ri_2")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_2, 1, 2, 1, 1)

        self.label_Welli_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_13.setObjectName("label_Welli_13")
        self.gridLayout.addWidget(self.label_Welli_13, 6, 0, 1, 1)

        self.lineEdit_Welli_Phii_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_5.setObjectName("lineEdit_Welli_Phii_5")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_5, 4, 3, 1, 1)

        self.lineEdit_Welli_Skin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_4.setObjectName("lineEdit_Welli_Skin_4")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_4, 3, 5, 1, 1)

        self.lineEdit_Welli_Pwf_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_7.setObjectName("lineEdit_Welli_Pwf_7")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_7, 6, 1, 1, 1)

        self.lineEdit_Welli_Ri_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_3.setObjectName("lineEdit_Welli_Ri_3")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_3, 2, 2, 1, 1)

        self.lineEdit_Welli_Phii_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_7.setObjectName("lineEdit_Welli_Phii_7")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_7, 6, 3, 1, 1)

        self.lineEdit_Welli_Phii_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_6.setObjectName("lineEdit_Welli_Phii_6")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_6, 5, 3, 1, 1)

        self.lineEdit_Welli_Rw_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_3.setObjectName("lineEdit_Welli_Rw_3")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_3, 2, 4, 1, 1)

        self.lineEdit_Welli_Rw_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_1.setObjectName("lineEdit_Welli_Rw_1")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_1, 0, 4, 1, 1)

        self.lineEdit_Welli_Ri_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_6.setObjectName("lineEdit_Welli_Ri_6")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_6, 5, 2, 1, 1)

        self.lineEdit_Welli_Ri_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_7.setObjectName("lineEdit_Welli_Ri_7")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_7, 6, 2, 1, 1)

        self.lineEdit_Welli_Ri_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_5.setObjectName("lineEdit_Welli_Ri_5")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_5, 4, 2, 1, 1)

        self.lineEdit_Welli_Pwf_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_4.setObjectName("lineEdit_Welli_Pwf_4")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_4, 3, 1, 1, 1)

        self.lineEdit_Welli_Rw_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_7.setObjectName("lineEdit_Welli_Rw_7")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_7, 6, 4, 1, 1)

        self.lineEdit_Welli_Skin_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_3.setObjectName("lineEdit_Welli_Skin_3")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_3, 2, 5, 1, 1)

        self.lineEdit_Welli_Skin_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_2.setObjectName("lineEdit_Welli_Skin_2")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_2, 1, 5, 1, 1)

        self.lineEdit_Welli_Pwf_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_1.setObjectName("lineEdit_Welli_Pwf_1")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_1, 0, 1, 1, 1)

        self.lineEdit_Welli_Pwf_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_2.setObjectName("lineEdit_Welli_Pwf_2")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_2, 1, 1, 1, 1)

        self.label_Welli_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_12.setObjectName("label_Welli_12")
        self.gridLayout.addWidget(self.label_Welli_12, 5, 0, 1, 1)

        self.lineEdit_Welli_Pwf_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_5.setObjectName("lineEdit_Welli_Pwf_5")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_5, 4, 1, 1, 1)

        self.lineEdit_Welli_Phii_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_1.setObjectName("lineEdit_Welli_Phii_1")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_1, 0, 3, 1, 1)

        self.lineEdit_Welli_Skin_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_6.setObjectName("lineEdit_Welli_Skin_6")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_6, 5, 5, 1, 1)

        self.lineEdit_Welli_Rw_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_2.setObjectName("lineEdit_Welli_Rw_2")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_2, 1, 4, 1, 1)

        self.lineEdit_Welli_Pwf_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_6.setObjectName("lineEdit_Welli_Pwf_6")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_6, 5, 1, 1, 1)

        self.lineEdit_Welli_Skin_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_5.setObjectName("lineEdit_Welli_Skin_5")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_5, 4, 5, 1, 1)

        self.label_Welli_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_2.setObjectName("label_Welli_2")
        self.gridLayout.addWidget(self.label_Welli_2, 0, 0, 1, 1)

        self.label_Welli_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_5.setObjectName("label_Welli_5")
        self.gridLayout.addWidget(self.label_Welli_5, 3, 0, 1, 1)

        self.lineEdit_Welli_Rw_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_4.setObjectName("lineEdit_Welli_Rw_4")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_4, 3, 4, 1, 1)

        self.lineEdit_Welli_Phii_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_2.setObjectName("lineEdit_Welli_Phii_2")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_2, 1, 3, 1, 1)

        self.lineEdit_Welli_Ri_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_4.setObjectName("lineEdit_Welli_Ri_4")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_4, 3, 2, 1, 1)

        self.label_Welli_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_4.setObjectName("label_Welli_4")
        self.gridLayout.addWidget(self.label_Welli_4, 2, 0, 1, 1)

        self.lineEdit_Welli_Rw_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_6.setObjectName("lineEdit_Welli_Rw_6")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_6, 5, 4, 1, 1)

        self.lineEdit_Welli_Ri_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_1.setObjectName("lineEdit_Welli_Ri_1")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_1, 0, 2, 1, 1)

        self.lineEdit_Welli_Phii_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_3.setObjectName("lineEdit_Welli_Phii_3")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_3, 2, 3, 1, 1)

        self.label_Welli_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_6.setObjectName("label_Welli_6")
        self.gridLayout.addWidget(self.label_Welli_6, 4, 0, 1, 1)

        self.label_Welli_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_3.setObjectName("label_Welli_3")
        self.gridLayout.addWidget(self.label_Welli_3, 1, 0, 1, 1)

        self.label_Welli_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Welli_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_14.setObjectName("label_Welli_14")
        self.gridLayout.addWidget(self.label_Welli_14, 7, 0, 1, 1)

        self.lineEdit_Welli_Pwf_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_3.setObjectName("lineEdit_Welli_Pwf_3")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_3, 2, 1, 1, 1)

        self.lineEdit_Welli_Rw_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_5.setObjectName("lineEdit_Welli_Rw_5")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_5, 4, 4, 1, 1)

        self.lineEdit_Welli_Skin_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_1.setObjectName("lineEdit_Welli_Skin_1")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_1, 0, 5, 1, 1)

        self.lineEdit_Welli_Phii_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_4.setObjectName("lineEdit_Welli_Phii_4")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_4, 3, 3, 1, 1)

        self.lineEdit_Welli_Pwf_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Pwf_8.setObjectName("lineEdit_Welli_Pwf_8")
        self.gridLayout.addWidget(self.lineEdit_Welli_Pwf_8, 7, 1, 1, 1)

        self.lineEdit_Welli_Ri_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Ri_8.setObjectName("lineEdit_Welli_Ri_8")
        self.gridLayout.addWidget(self.lineEdit_Welli_Ri_8, 7, 2, 1, 1)

        self.lineEdit_Welli_Phii_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Phii_8.setObjectName("lineEdit_Welli_Phii_8")
        self.gridLayout.addWidget(self.lineEdit_Welli_Phii_8, 7, 3, 1, 1)

        self.lineEdit_Welli_Rw_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Rw_8.setObjectName("lineEdit_Welli_Rw_8")
        self.gridLayout.addWidget(self.lineEdit_Welli_Rw_8, 7, 4, 1, 1)

        self.lineEdit_Welli_Skin_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Welli_Skin_8.setObjectName("lineEdit_Welli_Skin_8")
        self.gridLayout.addWidget(self.lineEdit_Welli_Skin_8, 7, 5, 1, 1)
        self.scrollArea_Wells_Area.setWidget(self.scrollAreaWidgetContents)

        # # images area
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(320, 10, 731, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_Images = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_Images.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Images.setObjectName("horizontalLayout_Images")
        # scheme
        self.label_Scheme = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Scheme.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Scheme.setText("")
        self.label_Scheme.setPixmap(QtGui.QPixmap("images/scheme_img.png"))
        self.label_Scheme.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Scheme.setObjectName("label_Scheme")
        self.horizontalLayout_Images.addWidget(self.label_Scheme)
        # units
        self.label_Unit_explanation = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Unit_explanation.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Unit_explanation.setText("")
        self.label_Unit_explanation.setPixmap(QtGui.QPixmap("images/unit_explanation.png"))
        self.label_Unit_explanation.setScaledContents(True)
        self.label_Unit_explanation.setObjectName("label_Unit_explanation")
        self.horizontalLayout_Images.addWidget(self.label_Unit_explanation)

        # # add/remove row buttons are
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1070, 370, 31, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_AddRemove_Buttons = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_AddRemove_Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_AddRemove_Buttons.setHorizontalSpacing(0)
        self.gridLayout_AddRemove_Buttons.setObjectName("gridLayout_AddRemove_Buttons")
        # remove
        self.pushButton_RemoveWell = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.pushButton_RemoveWell.setFont(font)
        self.pushButton_RemoveWell.setStyleSheet("background-color: rgb(138, 138, 138)")
        self.pushButton_RemoveWell.setObjectName("pushButton_RemoveWell")
        self.gridLayout_AddRemove_Buttons.addWidget(self.pushButton_RemoveWell, 1, 0, 1, 1)
        # add
        self.pushButton_AddWell = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)

        self.pushButton_AddWell.setFont(font)
        self.pushButton_AddWell.setStyleSheet("background-color: rgb(226, 226, 226)")
        self.pushButton_AddWell.setObjectName("pushButton_AddWell")
        self.gridLayout_AddRemove_Buttons.addWidget(self.pushButton_AddWell, 0, 0, 1, 1)

        # # action buttons area
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 430, 141, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_Calculate_Buttons = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_Calculate_Buttons.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Calculate_Buttons.setObjectName("gridLayout_Calculate_Buttons")
        # calculate
        self.pushButton_Calculate = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)

        self.pushButton_Calculate.setFont(font)
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.gridLayout_Calculate_Buttons.addWidget(self.pushButton_Calculate, 0, 0, 1, 1)
        # save
        self.pushButton_SavResults = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)

        self.pushButton_SavResults.setFont(font)
        self.pushButton_SavResults.setObjectName("pushButton_SavResults")
        self.gridLayout_Calculate_Buttons.addWidget(self.pushButton_SavResults, 1, 0, 1, 1)

        # # reservoir
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(210, 350, 311, 161))
        self.layoutWidget2.setObjectName("layoutWidget2")
        # gird layer
        self.gridLayout_Resv_Layer = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_Resv_Layer.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Resv_Layer.setObjectName("gridLayout_Resv_Layer")
        # P_e label
        self.label_resvPe = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_resvPe.setFont(font)
        self.label_resvPe.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resvPe.setObjectName("label_resvPe")
        self.gridLayout_Resv_Layer.addWidget(self.label_resvPe, 0, 0, 1, 1)
        # PHI label
        self.label__resvPHI = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label__resvPHI.setFont(font)
        self.label__resvPHI.setAlignment(QtCore.Qt.AlignCenter)
        self.label__resvPHI.setObjectName("label__resvPHI")
        self.gridLayout_Resv_Layer.addWidget(self.label__resvPHI, 0, 1, 1, 1)
        # r_e label
        self.label__resvRe = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label__resvRe.setFont(font)
        self.label__resvRe.setAlignment(QtCore.Qt.AlignCenter)
        self.label__resvRe.setObjectName("label__resvRe")
        # H label
        self.gridLayout_Resv_Layer.addWidget(self.label__resvRe, 0, 2, 1, 1)
        self.label__resvH = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label__resvH.setFont(font)
        self.label__resvH.setAlignment(QtCore.Qt.AlignCenter)
        self.label__resvH.setObjectName("label__resvH")
        # input label P_e
        self.gridLayout_Resv_Layer.addWidget(self.label__resvH, 0, 3, 1, 1)
        self.lineEdit_resvPe = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_resvPe.setFont(font)
        self.lineEdit_resvPe.setObjectName("lineEdit_resvPe")
        # input label PHI
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit_resvPe, 1, 0, 1, 1)
        self.lineEdit_resvPHI = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_resvPHI.setFont(font)
        self.lineEdit_resvPHI.setObjectName("lineEdit_resvPHI")
        # input label r_e
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit_resvPHI, 1, 1, 1, 1)
        self.lineEdit__resvRe = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvRe.setFont(font)
        self.lineEdit__resvRe.setObjectName("lineEdit__resvRe")
        # input label H
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvRe, 1, 2, 1, 1)
        self.lineEdit__resvH = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvH.setFont(font)
        self.lineEdit__resvH.setObjectName("lineEdit__resvH")
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvH, 1, 3, 1, 1)
        # K_r label
        self.label__resvKr = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label__resvKr.setFont(font)
        self.label__resvKr.setAlignment(QtCore.Qt.AlignCenter)
        self.label__resvKr.setObjectName("label__resvKr")
        # K_z label
        self.gridLayout_Resv_Layer.addWidget(self.label__resvKr, 2, 0, 1, 1)
        self.label__resvKz = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label__resvKz.setFont(font)
        self.label__resvKz.setAlignment(QtCore.Qt.AlignCenter)
        self.label__resvKz.setObjectName("label__resvKz")
        # input label K_r
        self.gridLayout_Resv_Layer.addWidget(self.label__resvKz, 2, 1, 1, 2)
        self.lineEdit__resvKr = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvKr.setFont(font)
        self.lineEdit__resvKr.setObjectName("lineEdit__resvKr")
        # input label K_z
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvKr, 3, 0, 1, 1)
        self.lineEdit__resvKz = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvKz.setFont(font)
        self.lineEdit__resvKz.setObjectName("lineEdit__resvKz")
        # mu label
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvKz, 3, 1, 1, 2)
        self.label_resvMu = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_resvMu.setFont(font)
        self.label_resvMu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resvMu.setObjectName("label_resvMu")
        # B label
        self.gridLayout_Resv_Layer.addWidget(self.label_resvMu, 4, 0, 1, 1)
        self.label_resvB = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_resvB.setFont(font)
        self.label_resvB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resvB.setObjectName("label_resvB")
        # input label mu
        self.gridLayout_Resv_Layer.addWidget(self.label_resvB, 4, 1, 1, 2)
        self.lineEdit__resvMu = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvMu.setFont(font)
        self.lineEdit__resvMu.setObjectName("lineEdit__resvMu")
        # input label B
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvMu, 5, 0, 1, 1)
        self.lineEdit__resvB = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit__resvB.setFont(font)
        self.lineEdit__resvB.setObjectName("lineEdit__resvB")

        # # well grid captions
        self.gridLayout_Resv_Layer.addWidget(self.lineEdit__resvB, 5, 1, 1, 2)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(580, 350, 451, 18))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # pwf label
        self.label_Well_Pwf = QtWidgets.QLabel(self.layoutWidget3)
        self.label_Well_Pwf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Well_Pwf.setObjectName("label_Well_Pwf")
        self.horizontalLayout_2.addWidget(self.label_Well_Pwf)
        # ri label
        self.label__Well_Ri = QtWidgets.QLabel(self.layoutWidget3)
        self.label__Well_Ri.setAlignment(QtCore.Qt.AlignCenter)
        self.label__Well_Ri.setObjectName("label__Well_Ri")
        self.horizontalLayout_2.addWidget(self.label__Well_Ri)
        # phii label
        self.label__Well_Phii = QtWidgets.QLabel(self.layoutWidget3)
        self.label__Well_Phii.setAlignment(QtCore.Qt.AlignCenter)
        self.label__Well_Phii.setObjectName("label__Well_Phii")
        self.horizontalLayout_2.addWidget(self.label__Well_Phii)
        # rw label
        self.label__Well_Rw = QtWidgets.QLabel(self.layoutWidget3)
        self.label__Well_Rw.setAlignment(QtCore.Qt.AlignCenter)
        self.label__Well_Rw.setObjectName("label__Well_Rw")
        self.horizontalLayout_2.addWidget(self.label__Well_Rw)
        # skin label
        self.label__Well_Skin = QtWidgets.QLabel(self.layoutWidget3)
        self.label__Well_Skin.setAlignment(QtCore.Qt.AlignCenter)
        self.label__Well_Skin.setObjectName("label__Well_Skin")
        self.horizontalLayout_2.addWidget(self.label__Well_Skin)

        # # captions
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(210, 310, 851, 20))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_Captions = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_Captions.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Captions.setObjectName("horizontalLayout_Captions")
        self.label_Reservoir = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        # label reservoir
        self.label_Reservoir.setFont(font)
        self.label_Reservoir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Reservoir.setObjectName("label_Reservoir")
        self.horizontalLayout_Captions.addWidget(self.label_Reservoir)
        self.label_Well = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        # well label
        self.label_Well.setFont(font)
        self.label_Well.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Well.setObjectName("label_Well")
        self.horizontalLayout_Captions.addWidget(self.label_Well)

        # # radio buttons
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 20, 71, 53))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_ModeChoice_Flags = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_ModeChoice_Flags.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_ModeChoice_Flags.setObjectName("gridLayout_ModeChoice_Flags")
        self.radioButton_Q = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_Q.setFont(font)
        self.radioButton_Q.setObjectName("radioButton_Q")
        self.gridLayout_ModeChoice_Flags.addWidget(self.radioButton_Q, 0, 0, 1, 1)
        self.radioButton_S = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_S.setFont(font)
        self.radioButton_S.setObjectName("radioButton_S")
        self.gridLayout_ModeChoice_Flags.addWidget(self.radioButton_S, 1, 0, 1, 1)


        # # results
        self.label_Results = QtWidgets.QLabel(self.centralwidget)
        self.label_Results.setGeometry(QtCore.QRect(80, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)

        self.label_Results.setFont(font)
        self.label_Results.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Results.setObjectName("label_Results")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 160, 161, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 138, 263))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Welli_result1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1.setObjectName("label_Welli_result1")
        self.gridLayout_2.addWidget(self.label_Welli_result1, 0, 0, 1, 1)
        self.label_Welli_result1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_3.setObjectName("label_Welli_result1_3")
        self.gridLayout_2.addWidget(self.label_Welli_result1_3, 2, 0, 1, 1)
        self.label_Welli_result1_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_7.setObjectName("label_Welli_result1_7")
        self.gridLayout_2.addWidget(self.label_Welli_result1_7, 6, 0, 1, 1)
        self.lineEdit_Welli_result1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1.setObjectName("lineEdit_Welli_result1")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1, 0, 1, 1, 1)
        self.label_Welli_result1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_4.setObjectName("label_Welli_result1_4")
        self.gridLayout_2.addWidget(self.label_Welli_result1_4, 3, 0, 1, 1)
        self.label_Welli_result1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_2.setObjectName("label_Welli_result1_2")
        self.gridLayout_2.addWidget(self.label_Welli_result1_2, 1, 0, 1, 1)
        self.label_Welli_result1_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_5.setObjectName("label_Welli_result1_5")
        self.gridLayout_2.addWidget(self.label_Welli_result1_5, 4, 0, 1, 1)
        self.label_Welli_result1_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_6.setObjectName("label_Welli_result1_6")
        self.gridLayout_2.addWidget(self.label_Welli_result1_6, 5, 0, 1, 1)
        self.label_Welli_result1_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_Welli_result1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Welli_result1_8.setObjectName("label_Welli_result1_8")
        self.gridLayout_2.addWidget(self.label_Welli_result1_8, 7, 0, 1, 1)
        self.lineEdit_Welli_result1_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_2.setObjectName("lineEdit_Welli_result1_2")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_2, 1, 1, 1, 1)
        self.lineEdit_Welli_result1_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_3.setObjectName("lineEdit_Welli_result1_3")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_3, 2, 1, 1, 1)
        self.lineEdit_Welli_result1_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_4.setObjectName("lineEdit_Welli_result1_4")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_4, 3, 1, 1, 1)
        self.lineEdit_Welli_result1_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_5.setObjectName("lineEdit_Welli_result1_5")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_5, 4, 1, 1, 1)
        self.lineEdit_Welli_result1_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_6.setObjectName("lineEdit_Welli_result1_6")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_6, 5, 1, 1, 1)
        self.lineEdit_Welli_result1_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_7.setObjectName("lineEdit_Welli_result1_7")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_7, 6, 1, 1, 1)
        self.lineEdit_Welli_result1_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_Welli_result1_8.setObjectName("lineEdit_Welli_result1_8")
        self.gridLayout_2.addWidget(self.lineEdit_Welli_result1_8, 7, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        # result label
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setGeometry(QtCore.QRect(64, 140, 90, 20))
        self.label_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result.setObjectName("label_Result")

        self.label_Result_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_Result_2.setGeometry(QtCore.QRect(190, 140, 91, 20))
        self.label_Result_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result_2.setObjectName("label_Result_2")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 160, 91, 22))
        self.lineEdit.setObjectName("lineEdit")

        # excel buttons
        self.pushButton_Excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Excel.setGeometry(QtCore.QRect(130, 60, 171, 31))
        self.pushButton_Excel.setObjectName("pushButton_Excel")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 171, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # # setting default values
        # reservoir properties
        self.lineEdit_resvPe.setText('18.0')
        self.lineEdit_resvPHI.setText('50')
        self.lineEdit__resvRe.setText('2500')
        self.lineEdit__resvH.setText('20')
        self.lineEdit__resvKr.setText('0.1')
        self.lineEdit__resvKz.setText('0.025')
        self.lineEdit__resvMu.setText('5.0')
        self.lineEdit__resvB.setText('1.25')
        # well's properties
        # well_1
        self.lineEdit_Welli_Pwf_1.setText('5.1')
        self.lineEdit_Welli_Ri_1.setText('300')
        self.lineEdit_Welli_Phii_1.setText('5')
        self.lineEdit_Welli_Rw_1.setText('0.1')
        self.lineEdit_Welli_Skin_1.setText('5')
        # well_2
        self.lineEdit_Welli_Pwf_2.setText('5.2')
        self.lineEdit_Welli_Ri_2.setText('400')
        self.lineEdit_Welli_Phii_2.setText('10')
        self.lineEdit_Welli_Rw_2.setText('0.1')
        self.lineEdit_Welli_Skin_2.setText('5')
        # well_3
        self.lineEdit_Welli_Pwf_3.setText('6.4')
        self.lineEdit_Welli_Ri_3.setText('800')
        self.lineEdit_Welli_Phii_3.setText('15')
        self.lineEdit_Welli_Rw_3.setText('0.1')
        self.lineEdit_Welli_Skin_3.setText('5')
        # well_4
        self.lineEdit_Welli_Pwf_4.setText('5.5')
        self.lineEdit_Welli_Ri_4.setText('1000')
        self.lineEdit_Welli_Phii_4.setText('20')
        self.lineEdit_Welli_Rw_4.setText('0.1')
        self.lineEdit_Welli_Skin_4.setText('5')
        # well_5
        self.lineEdit_Welli_Pwf_5.setText('4.8')
        self.lineEdit_Welli_Ri_5.setText('200')
        self.lineEdit_Welli_Phii_5.setText('25')
        self.lineEdit_Welli_Rw_5.setText('0.1')
        self.lineEdit_Welli_Skin_5.setText('5')
        # well_6
        self.lineEdit_Welli_Pwf_6.setText('8.7')
        self.lineEdit_Welli_Ri_6.setText('1500')
        self.lineEdit_Welli_Phii_6.setText('30')  # phi_i
        self.lineEdit_Welli_Rw_6.setText('0.1')  # r_w
        self.lineEdit_Welli_Skin_6.setText('5')  # skin
        # well_7
        self.lineEdit_Welli_Pwf_7.setText('5.8')
        self.lineEdit_Welli_Ri_7.setText('600')
        self.lineEdit_Welli_Phii_7.setText('35')  # phi_i
        self.lineEdit_Welli_Rw_7.setText('0.1')  # r_w
        self.lineEdit_Welli_Skin_7.setText('5')  # skin
        # well_8
        self.lineEdit_Welli_Pwf_8.setText('9.3')  # p_wf
        self.lineEdit_Welli_Ri_8.setText('2000')  # r_i
        self.lineEdit_Welli_Phii_8.setText('40')  # phi_i
        self.lineEdit_Welli_Rw_8.setText('0.1')  # r_w
        self.lineEdit_Welli_Skin_8.setText('5')  # skin

        # # connect actions to the buttons
        self.pushButton_Calculate.clicked.connect(self.do_calculation)
        self.pushButton_Excel.clicked.connect(self.manage_excel)
        self.pushButton_SavResults.clicked.connect(self.save_results)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # # by default chose Q_mode
        self.radioButton_Q.setChecked(True)
        # assign actions
        self.radioButton_S.toggled.connect(self.change_mode_to_s)
        self.radioButton_Q.toggled.connect(self.change_mode_to_q)

    def retranslateUi(self, MainWindow):
        window_name = "Steady-State Productivity Equations for a Multiple-Wells System in Sector Fault Reservoirs"
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", window_name))
        self.label_Welli_13.setText(_translate("MainWindow", "Well 7"))
        self.label_Welli_12.setText(_translate("MainWindow", "Well 6"))
        self.label_Welli_2.setText(_translate("MainWindow", "Well 1"))
        self.label_Welli_5.setText(_translate("MainWindow", "Well 4"))
        self.label_Welli_4.setText(_translate("MainWindow", "Well 3"))
        self.label_Welli_6.setText(_translate("MainWindow", "Well 5"))
        self.label_Welli_3.setText(_translate("MainWindow", "Well 2"))
        self.label_Welli_14.setText(_translate("MainWindow", "Well 8"))
        self.pushButton_RemoveWell.setText(_translate("MainWindow", "-"))
        self.pushButton_AddWell.setText(_translate("MainWindow", "+"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_SavResults.setText(_translate("MainWindow", "Save results"))
        self.label_resvPe.setText(_translate("MainWindow", "P_e, MPa "))
        self.label__resvPHI.setText(_translate("MainWindow", "PHI, deg"))
        self.label__resvRe.setText(_translate("MainWindow", "r_e, m "))
        self.label__resvH.setText(_translate("MainWindow", "H, m"))
        self.label__resvKr.setText(_translate("MainWindow", "K_r, m^2*e-6"))
        self.label__resvKz.setText(_translate("MainWindow", "K_z, m^2*e-6"))
        self.label_resvMu.setText(_translate("MainWindow", "mu, mPa*s"))
        self.label_resvB.setText(_translate("MainWindow", "B, m^3/m^3"))
        self.label_Well_Pwf.setText(_translate("MainWindow", "P_wf, MPa"))
        self.label__Well_Ri.setText(_translate("MainWindow", "r_i, m"))
        self.label__Well_Phii.setText(_translate("MainWindow", "phi_i, deg"))
        self.label__Well_Rw.setText(_translate("MainWindow", "r_w, m"))
        self.label__Well_Skin.setText(_translate("MainWindow", "skin"))
        self.label_Reservoir.setText(_translate("MainWindow", "Reservoir properties"))
        self.label_Well.setText(_translate("MainWindow", "Well\'s properties"))
        self.radioButton_Q.setText(_translate("MainWindow", "Find Q"))
        self.radioButton_S.setText(_translate("MainWindow", "Find S"))
        self.label_Results.setText(_translate("MainWindow", "Results"))
        self.label_Welli_result1.setText(_translate("MainWindow", "Well 1"))
        self.label_Welli_result1_3.setText(_translate("MainWindow", "Well 3"))
        self.label_Welli_result1_7.setText(_translate("MainWindow", "Well 7"))
        self.label_Welli_result1_4.setText(_translate("MainWindow", "Well 4"))
        self.label_Welli_result1_2.setText(_translate("MainWindow", "Well 2"))
        self.label_Welli_result1_5.setText(_translate("MainWindow", "Well 5"))
        self.label_Welli_result1_6.setText(_translate("MainWindow", "Well 6"))
        self.label_Welli_result1_8.setText(_translate("MainWindow", "Well 8"))
        self.label_Result.setText(_translate("MainWindow", "Q, m^3/d"))
        self.label_Result_2.setText(_translate("MainWindow", "Q_sum, m^3/d"))
        self.pushButton_Excel.setText(_translate("MainWindow", "Calculate from Excel file"))
        self.label.setText(_translate("MainWindow", "PATH to Excel file"))

    def do_calculation(self):
        # # data collecting
        self.well_input = self._well_data_prep()
        self.reservoir_input = self._reservoir_data_prep()

        # # calculations
        if self.radioButton_S.isChecked():
            skinlist = sspeq.find_s(self.well_input, self.reservoir_input)
            self.skin_solution = skinlist[:]
            # # show results
            # well skin
            for widget in (self.gridLayout_2.itemAt(i).widget() for i in
                           range(self.gridLayout_2.count())):
                if isinstance(widget, QtWidgets.QLineEdit):
                    widget.setText(str(round(skinlist.pop(0), 2)))

        elif self.radioButton_Q.isChecked():
            sumrate, ratelist = sspeq.find_q(self.well_input, self.reservoir_input)
            self.sumrate_solution = sumrate
            self.rate_solution = ratelist[:]
                # # show results
            # sum rate
            self.lineEdit.setText(str(round(sumrate, 2)))
            # well rate
            for widget in (self.gridLayout_2.itemAt(i).widget() for i in
                           range(self.gridLayout_2.count())):
                if isinstance(widget, QtWidgets.QLineEdit):
                    widget.setText(str(round(ratelist.pop(0), 2)))

    def save_results(self):
        save_file = pd.DataFrame()
        # for find_S
        # print(self.well_input)
        mode_marker = 'skin' if self.radioButton_Q.isChecked() else 'Q' if self.radioButton_S.isChecked() else 'Err'
        try:
            well_input_df = pd.DataFrame([['p_wf', 'r_i', 'phi_i', 'r_w', f'{mode_marker}'], *self.well_input])
            resv_input_df = pd.DataFrame([('p_e', 'r_e', 'PHI', 'h', 'k_r', 'k_z', 'mu', 'B'), self.reservoir_input]
                                         )
            combo = pd.concat([pd.DataFrame(['WELL']), well_input_df, pd.DataFrame(['RESV']), resv_input_df])
            input_save = pd.concat([pd.DataFrame(['CASE MANUAL', 'INPUT']), combo])

            if self.radioButton_Q.isChecked():
                well_numeration = [f'well {i + 1}' for i in range(len(self.rate_solution))] + ['SUM']
                q_vec = self.rate_solution + [self.sumrate_solution]
            else:
                well_numeration = [f'well {i + 1}' for i in range(len(self.rate_solution))]
                q_vec = self.rate_solution

            solution = pd.concat([pd.DataFrame(['', f'{"Q (rate)" if self.radioButton_Q.isChecked() else "SKIN"}']),
                                  pd.DataFrame([well_numeration, q_vec])])

            save_file = pd.concat([save_file, input_save, solution])

            save_file.to_excel('manual_save_test.xlsx', index=False, header=False)
        except AttributeError:
            pass

    def _well_data_prep(self):
        # collect well info
        wells_prop_dict = {}
        for widget in (self.gridLayout.itemAt(i).widget() for i in range(self.gridLayout.count())):
            if isinstance(widget, QtWidgets.QLineEdit):
                # print(f"linedit: {widget.objectName()}  - {widget.text()} : {i}, type : {type(widget.objectName())}")
                if widget.objectName()[-1] in wells_prop_dict:
                    pass
                else:
                    wells_prop_dict[widget.objectName()[-1]] = {}

                if 'Pwf' in widget.objectName():
                    wells_prop_dict[widget.objectName()[-1]]['Pwf'] = float(widget.text())

                elif 'Ri' in widget.objectName():
                    wells_prop_dict[widget.objectName()[-1]]['Ri'] = (float(widget.text()))

                elif 'Phii' in widget.objectName():
                    wells_prop_dict[widget.objectName()[-1]]['Phii'] = float(widget.text())

                elif 'Rw' in widget.objectName():
                    wells_prop_dict[widget.objectName()[-1]]['Rw'] = float(widget.text())
                # skin/q
                elif 'Skin' in widget.objectName():
                    wells_prop_dict[widget.objectName()[-1]]['Skin'] = float(widget.text())
        # # restructure data according to functions template
        # wells
        well_input = []
        for key in sorted(wells_prop_dict):
            values = []
            for value in ('Pwf', 'Ri', 'Phii', 'Rw', 'Skin'):
                values.append(wells_prop_dict[key][value])

            well_input.append(tuple(values))
        well_input = tuple(well_input)
        return well_input

    def _reservoir_data_prep(self):
        # collect reservoir info
        resv_prop_dict = {}
        for widget in (self.gridLayout_Resv_Layer.itemAt(i).widget() for i in
                       range(self.gridLayout_Resv_Layer.count())):
            if isinstance(widget, QtWidgets.QLineEdit):
                resv_prop_dict[widget.objectName()[13:].replace('v', '')] = float(widget.text())

        reservoir_input = []
        for key in ('Pe', 'Re', 'PHI', 'H', 'Kr', 'Kz', 'Mu', 'B'):
            reservoir_input.append(resv_prop_dict[key])
        reservoir_input = tuple(reservoir_input)
        return reservoir_input

    def manage_excel(self):
        file_path = repr(self.lineEdit_2.text()).replace("'", '').replace('"', '')
        try:
            input_file = pd.read_excel(file_path, header=None)
        except TypeError:
            print('No such directory')
            return None
        except FileNotFoundError:
            print('No such file')
            return None

        start_i, end_i = self._get_case_bound(input_file)

        output_file = pd.DataFrame()

        for i in range(len(start_i)):
            case_i = input_file.iloc[[_ for _ in range(start_i[i] + 1, end_i[i])]].reset_index(drop=True)

            resv_i, wells_i, mode = self._split_properties(case_i)
            if mode == 'SKIN':
                q_sum, q = sspeq.find_q(wells_i, *resv_i)
                # print(f'CASE {i}\t{mode} is known\nQ_sum : {q_sum: .3f}\nQ_vec : {[round(_, 2) for _ in q]}')
                well_numeration = [f'well {i + 1}' for i in range(len(q))] + ['SUM']
                q_vec = q + [q_sum]
                solution = pd.concat([pd.DataFrame([f'CASE {i}', 'Q (rate)']), pd.DataFrame([well_numeration, q_vec])])

                output_file = pd.concat([output_file, solution])

            elif mode == 'Q':
                s_vec = sspeq.find_s(wells_i, *resv_i)
                # print(f'CASE {i}\t{mode} is known\nS_vec : {[round(_, 2) for _ in s_vec]}')
                well_numeration = [f'well {i + 1}' for i in range(len(s_vec))]
                solution = pd.concat([pd.DataFrame([f'CASE {i}', 'SKIN']), pd.DataFrame([well_numeration, s_vec])])

                output_file = pd.concat([output_file, solution])

            else:
                pass

        output_file.to_excel('solution_test.xlsx', index=False, header=False)

    def _get_case_bound(self, dataframe):
        start = dataframe.index[dataframe[0] == 'START'].to_list()
        end = dataframe.index[dataframe[0] == 'END'].to_list()
        return start, end

    def _split_properties(self, dataframe):
        # boundaries
        resv_bound1 = int(dataframe.index[dataframe[0] == 'RESV'].to_list()[0])
        resv_bound2 = int(dataframe.index[dataframe[0] == 'WELL'].to_list()[0])
        # slicing
        resv_prop = dataframe.iloc[[_ for _ in range(resv_bound1 + 1, resv_bound2)]].reset_index(drop=True)
        well_prop = dataframe.iloc[resv_bound2 + 1:].reset_index(drop=True)
        # finishing
        resv_prop.columns = resv_prop.iloc[0]
        resv_prop = resv_prop[1:]

        mode_marker = well_prop.iloc[0].to_list()[5].upper()

        well_prop.columns = well_prop.iloc[0]
        well_prop = well_prop[1:].dropna(axis=1).drop(columns='index')

        return resv_prop.values.tolist(), well_prop.values.tolist(), mode_marker

    def change_mode_to_s(self):
        self.label_Result_2.hide()
        self.lineEdit.hide()
        self.label_Result.setText('Skin - factor')
        self.label__Well_Skin.setText('q, m^3/d')

    def change_mode_to_q(self):
        self.label_Result.setText('Q_sum, m^3/d')
        self.label__Well_Skin.setText('skin')
        self.label_Result_2.show()
        self.lineEdit.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
